easy_admin:
    site_name: 'Gabinet Stomatologiczny'
    formats:
        datetime: 'd/m/Y H:i:'
    design:
        menu:
            - { entity: 'Dentist', icon: 'user-nurse' }
            - { entity: 'Patient', icon: 'user' }
            - { entity: 'Visit', icon: 'calendar' }


    entities:

        Dentist:
            label: 'Stomatolodzy'
            class: App\Entity\Dentist
            search:
                fields:
                - 'FirstName'
                - 'LastName'
            show:
                fields:
                - 'FirstName'
                - 'LastName'
                - { property: 'visits', template: 'visits.html.twig'}

        Patient:
            class: App\Entity\Patient
            list:
                fields:
                    - {property: 'id'}
                    - {property: 'FirstName'}
                    - {property: 'LastName'}
            show:
                fields:
                - {label: 'Imię',property: 'FirstName'}
                - {label: 'Nazwisko', property: 'LastName'}
            edit:
                fields:
                    - {property: 'FirstName'}
                    - {property: 'LastName'}
        Specialization:
            class: App\Entity\Specialization
            list:
                - { property: 'visits', template: 'visits.html.twig'}
        Visit:
            class: App\Entity\Visit

            edit:
                fields:
                    - {property: 'descriptions'}






